# Generated by Django 4.1.3 on 2022-11-25 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_finance_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpenditure',
            name='time',
            field=models.DateField(default=datetime.date(2022, 11, 25)),
        ),
    ]
