# Generated by Django 4.1.3 on 2022-12-06 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_finance_daily_expenditure_user_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpenditure',
            name='time',
            field=models.DateField(default=datetime.date(2022, 12, 6)),
        ),
        migrations.AlterField(
            model_name='finance',
            name='add_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='finance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='finance',
            name='daily_cost_estimate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='finance',
            name='daily_expenditure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='finance',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='finance',
            name='saving_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='finance',
            name='total_expenditure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
